/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yk_cdemo_JniUtils */

#ifndef _Included_com_yk_cdemo_JniUtils
#define _Included_com_yk_cdemo_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yk_cdemo_JniUtils
 * Method:    add
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_com_yk_cdemo_JniUtils_add
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
